name: Graphbank_Frontend
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  http_server: '>=0.9.6'
  http: '>=0.11.3'
  browser: '>=0.10.0 <0.11.0'
  angular2: '>=2.2.0 <2.3.0'
  angular2_components: '>=0.2.2 <0.3.0'
  source_gen: '>=0.5.3'
  json_object: any
dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
- dart_to_js_script_rewriter
