name: Graphbank_Frontend
description: A Dart App that uses Angular 2
version: 0.0.1
environment:
  sdk: any
dependencies:
  http_server: any
  http: any
  browser: any
  angular2: any
  angular2_components: any
  source_gen: any
  json_object: any
dev_dependencies:
  dart_to_js_script_rewriter: any
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
- dart_to_js_script_rewriter
