language: java
jdk:
 - oraclejdk8
before_install:
 - cd Backend
 - ls
 - ./mvnw process-resources
addons:
  sonarqube:
    token:
      secure: ${sonar_token}
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar coveralls:report -Dspring.profiles.active=travis -DrepoToken=${coveralls_token}
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
