language: java
jdk:
 - oraclejdk8
before_install:
 - cd Backend
 - ls
 - ./mvnw install:install-file
addons:
  sonarqube:
    token:
      secure: ${sonar_token}
script:
  - mvn clean package org.jacoco:jacoco-maven-plugin:prepare-agent cobertura:cobertura sonar:sonar jacoco:report coveralls:report -Dspring.profiles.active=travis -DrepoToken=${coveralls_token}
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
