= Graph Bank

image:https://travis-ci.org/bindstone/graphbank.svg?branch=master["Build Status", link="https://travis-ci.org/bindstone/graphbank"]
image:https://api.codacy.com/project/badge/Grade/ed89c7d8d8a6421f811758f4ac45057f["Codacy code quality", link="https://www.codacy.com/app/bindstone/graphbank?utm_source=github.com&utm_medium=referral&utm_content=bindstone/graphbank&utm_campaign=Badge_Grade"]


https://sonarqube.com/dashboard/index?id=com.bindstone.graphbank%3Agraphbank_backend[Sonar Report]

=== Overview

This is an experimental project using the following technologies: #Java 8 #Spring #MyBatis #Neo4j #Activiti #Dart #Angular2

==== Code strategies

Java: Generics

Dart: Source_Gen _Dart files ending with .g.dart are not written but generated.

=== Preparation

For executing the source generation on Dart:

cd ./Frontend

dart tool/build.dart

For continuous source generation:

dart tool/watch.dart

For continuous development on Dart use:

pub serve

=== Building the project

cd Backend

mvn clean install

=== External services used in the project:

https://github.com/[GitHub] a web-based Git repository hosting service.

https://travis-ci.org/[Travis] automated code test and building service.

https://sonarqube.com/[SonarQube], https://www.codacy.com/[Codacy] Code quality service

http://www.graphenedb.com/[GraphenDB] Neo4J Cloud Graph Database.

https://activiti.alfresco.com/[Activiti] Activiti Alfresco BPM.